// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task.Repository;

#nullable disable

namespace Task.Repository.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Task.DTO.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Task.DTO.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Date")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("Date")
                        .HasAnnotation("CheckConstraint", "DateOfBirth <= DateAdd(Year, -18, GetDate())");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("Nvarchar(50)")
                        .HasAnnotation("MinLength", 2);

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("Nvarchar(50)")
                        .HasAnnotation("MinLength", 2);

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasColumnType("Nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Task.DTO.PhoneNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("Nvarchar(50)")
                        .HasAnnotation("MinLength", 4);

                    b.Property<int>("PersonIdId")
                        .HasColumnType("int");

                    b.Property<byte>("PhoneType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("PersonIdId");

                    b.ToTable("PhoneNumbers");
                });

            modelBuilder.Entity("Task.DTO.Relationship", b =>
                {
                    b.Property<int>("FromPersonId")
                        .HasColumnType("int");

                    b.Property<int>("ToPersonId")
                        .HasColumnType("int");

                    b.Property<byte>("RelationshipType")
                        .HasColumnType("tinyint");

                    b.HasKey("FromPersonId", "ToPersonId");

                    b.HasIndex("ToPersonId");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("Task.DTO.Person", b =>
                {
                    b.HasOne("Task.DTO.City", "City")
                        .WithMany("People")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Task.DTO.PhoneNumber", b =>
                {
                    b.HasOne("Task.DTO.Person", "PersonId")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("PersonIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonId");
                });

            modelBuilder.Entity("Task.DTO.Relationship", b =>
                {
                    b.HasOne("Task.DTO.Person", "FromPerson")
                        .WithMany("RelationshipFrom")
                        .HasForeignKey("FromPersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Task.DTO.Person", "ToPerson")
                        .WithMany("RelationshipTo")
                        .HasForeignKey("ToPersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FromPerson");

                    b.Navigation("ToPerson");
                });

            modelBuilder.Entity("Task.DTO.City", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("Task.DTO.Person", b =>
                {
                    b.Navigation("PhoneNumbers");

                    b.Navigation("RelationshipFrom");

                    b.Navigation("RelationshipTo");
                });
#pragma warning restore 612, 618
        }
    }
}
